title: The Workshop on<br>Democratizing Software Verification
description: July 19, 2020<br>colocated with CAV 2020:<br>The 32nd International Conference on Computer-Aided Verification
theme: jekyll-theme-cayman
github:
  is_project_page: false
